
version: '3.3'

services:

  mgdb-migrator-dev:
    image: mgdb-migrator:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mgdb-migrator-db
    environment:
      - 'DBURL=mongodb://mgdb-migrator-db:27017/mgdb-migrator-db'
      - 'NODE_ENV=developoment'
    volumes:
      - '.:/usr/src/mgdb-migrator'
    ports:
      # Warning: Binding to 0.0.0.0 without firewall protection opens
      # host up to outside access. Make sure to turn on firewall
      # if you are not testing from an exernal machine or device.
      - "0.0.0.0:5857-5870:5857-5870"

  mgdb-migrator-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 --smallfiles

  mgdb-migrator-test:
    image: mgdb-migrator:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mgdb-migrator-db
    environment:
      - 'DBURL=mongodb://mgdb-migrator-db:27017/mgdb-migrator-db'
      - 'NODE_ENV=test'

